### ISSUE TITLE
This may be of relevance / interest

### ISSUE THREAD

**Issue by markvanderloo** [RConsortium/RCDI-WG#2]
[Community principles](https://www.isi-web.org/index.php/about-isi/what-is-isi/community-principles) of the International Statistical Institute (ISI).

**Comment by joshuaulrich** [comment]
The original link is dead, but there is [one capture](https://web.archive.org/web/20180918052815/https://www.isi-web.org/index.php/about-isi/what-is-isi/community-principles) on the internet archive.  The text is below:

> ### ISI Community Principles
> A welcoming, supportive and harmonious community is critical to the productivity of any organization. As an organisation, ISI will strive to make sure that all members of the ISI and its Associations feel valued in their efforts to pursue the ISI Mission and Objectives. ISI will constantly and consistently work towards a sense of international community, wherein productive and collaborative networking and relationships are fostered worldwide. Debate is recognised and welcomed as a critical part of decision making; however, we expect this to occur in an atmosphere of civility and respect.
>
> As an international organisation, ISI is committed to acknowledging and taking account of all and any sensitivities across the diversity of individuals, countries and regions.  We encourage transparency and openness, while respecting the privacy of the members of our community.
>
> ISI is committed to providing a professional environment free from discrimination on the basis of sex, race, colour, religion, national origin, disability, age, sexual orientation, gender identity, and politics.
All members of ISI and its Associations are expected to adhere to these Community Principles.
>
> All participants in ISI and Association events are expected to display respect, professionalism and courtesy towards all other participants.
