### ISSUE TITLE
Code of conduct comments

### ISSUE THREAD

**Issue by karawoo** [RConsortium/RCDI-WG#5]
As discussed on 2 July, I've uploaded the [R-Ladies code of conduct](https://github.com/RConsortium/RCDI-WG/blob/a5ef0aaa63636d75c5d50208c98f66f8f55552f7/conduct/code-of-conduct.md) to the repo. I'm opening this issue to discuss any adaptations we'd like to make. If you have thoughts, feel free to leave them here.

**Comment by karawoo** [comment]
To recap comments that came up in the August 6th meeting (let me know if anyone feels I haven't captured these accurately):
* @joseph-rickert: current CoC explicitly applies to online spaces as well as in-person events and we should keep that.
* @joseph-rickert wanted to see the CoC framed in a more positive way around principles we'd like to uphold and not just things that are not allowed. @SamanthaToet suggested that concrete and specific examples of both acceptable and unacceptable behavior could be useful. @hadley and I also agreed specificity is important.

**Comment by karawoo** [comment]
Also, here are some resources on effective codes of conduct:
* [HOWTO design a code of conduct for your community](https://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/)
* [Code of conduct evaluations](http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations)

**Comment by joseph-rickert** [comment]
Thanks Kara,
Best,
Joe

**Comment by DragonflyStats** [comment]
Hi Folks
I just found some interesting resources on twitter:
https://twitter.com/InclusionInML/status/1027253622395031553

The text is:
Updated D&I page @NipsConference (https://nips.cc/public/DiversityInclusion …):
@WiMLworkshop: http://wimlworkshop.org/  
@black_in_ai: https://blackinai.github.io/  
Latinx in AI: http://www.latinxinai.org/nips-2018  
Queer in AI: https://queerai.github.io/QueerInAI/  
Jews in ML: https://www.cs.bgu.ac.il/~mlt142/JIML?format=standalone …

**Comment by DragonflyStats** [comment]
Also this one:
https://dublin2019.com/members-area/code-of-conduct/

Particularly as it gives some concrete examples ( see the Anti-racism statement section)

**Comment by DragonflyStats** [comment]
one more:
https://otter.technology/blog/2018/08/09/evolving-code-of-conduct-language/

Particularly use of phrases like reporter and reported person.

**Comment by hadley** [comment]
Some resources from Heather Turner:

* https://2018.djangocon.eu/conduct/
* PyCon CoC transparency report: https://pycon.blogspot.com/2018/06/pycon-2018-code-of-conduct-transparency.html
* Safe ISBA : https://bayesian.org/governance/code-of-conduct/; https://bayesian.org/governance/policies/ (edited)

**Comment by jmertic** [comment]
I'll also share ones from other Linux Foundation projects:

- ODPi CoC ( adapted from HyperLedger and others ) https://github.com/odpi/tsc/blob/master/governance/code_of_conduct.md
- LF events CoC https://events.linuxfoundation.org/code-of-conduct/

**Comment by gdequeiroz** [comment]
For R-Ladies, I remember we used a few resources to help and guide us.  Some resources we used:


- Django code of conduct at https://www.djangoproject.com/conduct/
- Geek Feminism at https://geekfeminism.org/about/code-of-conduct/
- Rust Lang at https://www.rust-lang.org/en-US/conduct.html
- http://geekfeminism.wikia.com/wiki/Community_anti-harassment/Policy

It was important for us to add at the very top all the things that are not allowed and what harassment includes.

**Comment by hadley** [comment]
And some great responses to code of conduct FAQs: https://www.ashedryden.com/blog/codes-of-conduct-101-faq

**Comment by karawoo** [comment]
I think this is overall a good example of a CoC and we could recommend it more or less as is to event organizers. It's basically the same as the Geek Feminism CoC, which has a lot of experience and expertise behind it.

There is one sentence in the Reporting section that I'd suggest changing:

> If the person who is harassing you is on the team, they will recuse themselves from handling your incident.

If someone is already harassing me, I'm not going to trust them to recuse themself from handling the incident report. I think instead other members of the team should be responsible for ensuring that someone who is accused of harassment isn't allowed to field harassment reports about themself. And there should be ways of reporting that support this -- I should be able to make a report directly to someone I trust, not just to an email address that may go to multiple people including the person I'm reporting on.
