### ISSUE TITLE
nick's comments on CoC

### ISSUE THREAD

**Issue by njtierney** [RConsortium/RCDI-WG#9]
# comment 1

CoC line 3:

>`<EVENT>` is a working conference intended for professional networking and collaboration in the R community.

# comment 2

Minor thing - but would it be clearer to say only "conference" instead of "working conference"?

# comment 3

Perhaps drop "developers" so it reads as:

> This code (CoC) applies to any participant at <EVENT>. This includes participants in meetings, teleconferences, mailing lists, conferences or functions, etc. Note that this code complements rather than replaces legal rights and obligations pertaining to any particular situation.

# comment 4

Typo: "Participants at <EVENT> may also participate"

# comment 5

I'm not sure where to mention this on the document, but [around here at consequences / support provided](https://github.com/RConsortium/RCDI-WG/blob/master/conduct/code-of-conduct.md#consequences) it might be worthwhile mentioning something about appropriate debriefing for the victim, and also those involved in reporting/assisting from conference staff. This helps ensure that those who help report or witness the event are safe and supported. The debriefing could also help provide feedback on how these situations are handled, so that they can be improved.

**Comment by karawoo** [comment]
Looks like 2 and 4 have already been addressed. I'm not sure what comment 1 is about?

For 5, I think that is something that doesn't belong in the code of conduct itself, but rather as part of a collection of resources we could provide organizers on enforcement/response. I think that should be a separate document. Does that sound ok to you?

**Comment by njtierney** [comment]
Yup, 2 and 4 are good to me, and 3 was addressed in #10 I believe. 

Comment 1 was a typo in that sentence.

For five, I think that a separate document would be the best place to put information about how to appropriately deliver support - it is a complex topic and not something for the CoC. 

Perhaps the CoC could make a mention to this document somewhere, so that people know that providing care of the victims and supporters is important.

My apologies for not replying to this in a timely manner, happy to open another issue if that makes it easier to track progress. 

Thank you all for working toward this, and for allowing me the opportunity to give feedback, I think the CoC looks fantastic!
